### ISSUE TITLE
Alias route `/home` for `/` throws error page

### ISSUE THREAD

**Issue by johannschopplich** [jmheretik/kirby-json-vue-starterkit#2]
Imagine some pages linking back to the homepage's native id `home`. But accessing `/home` throws the error page.

I've tried setting up an `alias` in the Vue router, which doesn't work. Then I've changed the config to return the homepage when the `home` is passed, which seems hacky. What I've come up with now is:

```js
const id = this.$route.path.substr(1) || 'home'

this.pageLoaded = new Promise(async resolve => {
  this.page = id === 'home' ? this.$home : await this.$api.getPage(id)

  await this.$nextTick()

  resolve()
})
```
(The homepage's data is saved in `Vue.protoype.$home` because otherwise it would be fetched twice.)

What would be your way-to-go for this problem?

**Comment by jmheretik** [comment]
Hey there! The alias should work correctly now with the last commit.

As for my personal opinion: I wouldnt use alias for `home` but rather a redirect. Because having duplicate urls with the same content is not considered a good practice (even kirby by itself automatically redirects `/home` to `/`) and is also bad for SEO I believe :)

**Comment by johannschopplich** [comment]
Thank you, seems to be an easy fix. 

From a SEO point of view, duplicate content is bad practice. True. Therefore the redirect is the perfect solution. 🙂
